---
# tasks file for roles/swarm-master

- name: Check if manager already configured
  shell: >
    docker info | perl -ne 'print "$1" if /Swarm: (\w+)/'
  register: swarm_status

- name: Init cluster
  shell: >-
    docker swarm init
    --advertise-addr "{{ ansible_default_ipv4.address }}"
  when: "'active' not in swarm_status.stdout_lines"

- name: Get worker token
  shell: docker swarm join-token -q worker
  register: worker_token_result

- set_fact:
    worker_token: "{{ worker_token_result.stdout  }}"
