- hosts: swarm_cluster
  become: yes
  roles:
    - docker

- hosts: swarm_cluster:&manager
  become: yes
  tasks:
    - name: Check if manager already configured
      shell: >
        docker info | perl -ne 'print "$1" if /Swarm: (\w+)/'
      register: swarm_status

    - name: Init cluster
      debug:
        msg: im here
        when: "'active' not in swarm_status.stdout_lines"
