- hosts: swarm_cluster
  become: yes
  tasks:
    - name: Install aptitude which makes apt module happy
      apt:
        name: aptitude
        state: latest
        update_cache: yes
        force_apt_get: yes

    - name: Install prerequisites
      apt: name={{ item }} state=latest
      loop:
        - 'apt-transport-https'
        - 'ca-certificates'
        - 'curl'
        - 'software-properties-common'
        - 'python3-pip'
        - 'virtualenv'
        - 'python3-setuptools'

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

- hosts: swarm_cluster:&manager
  become: yes
  tasks:
    - name: Check if manager already configured
      shell: >
        docker info | perl -ne 'print "$1" if /Swarm: (\w+)/'
      register: swarm_status

    - name: Init cluster
      debug:
        msg: im here
        when: "'active' not in swarm_status.stdout_lines"
