#- hosts: swarm_cluster
#  become: yes
#  roles:
#    - docker

- hosts: manager[0]
  become: yes
  tasks:
    - docker_swarm:
        state: present
      register: swarm_info
    - debug:
        msg: "{{ swarm_info.swarm_facts.JoinTokens.Worker }}"
