- hosts: swarm-cluster
  become: yes
  roles:
    - docker

- hosts: manager
  become: yes
  roles:
    - swarm-master

- hosts: node
  become: yes
  tasks:
    - debug:
        msg: "{{ hostvars[item]['worker_token'] }}"
      with_items: "{{ groups['manager'] }}"
